version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/8.2/default"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/8.2/imagick"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/8.3/default"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/8.4/default"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/8.5/default"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
