version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/7.4/default"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/7.4/imagick"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/8.0/default"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/8.0/imagick"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/8.1/default"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/8.1/imagick"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
