# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Our tag names are like v8.0.4, we want to see if 8.0 is in the default branch, this extracts the major.minor version
      - name: Extract the major.minor version from the tag
        id: get-tag-ver
        uses: actions/github-script@v6
        with:
          script: |
            const ver = context.ref.substring(context.ref.indexOf('/v')+2, context.ref.lastIndexOf('.'));
            core.setOutput('ver', ver)
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: uwischool/php-fpm
          tags: |
            type=raw,value=latest,enable=${{ !contains(github.ref, 'x') && startsWith(steps.get-tag-ver.outputs.ver, github.event.repository.default_branch) }}
            type=semver,pattern={{version}},enable=${{ !contains(github.ref, 'x') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ !contains(github.ref, 'x') }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
